default: &default
  adapter: postgresql
  encoding: unicode
  username: rey
  password: tuta2020
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: research_development

test:
  <<: *default
  database: research_test

production:
  <<: *default
  database: research_production
  username: research
  password: <%= ENV['RESEARCH_DATABASE_PASSWORD'] %>
